name: remote_kitchen_assessment_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter: 
    sdk: flutter
  hive_flutter: ^1.1.0
  

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.3.3

flutter: 
  uses-material-design: true

