name: remote_kitchen_assessment_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter: 
    sdk: flutter
  hive_flutter: ^1.1.0
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  lottie: ^3.1.2
  http: ^1.2.1
  google_maps_flutter: ^2.2.8
  google_maps_flutter_platform_interface: ^2.7.0
  google_maps_flutter_android: ^2.8.0
  uuid: ^4.4.0
  location: ^6.0.2
  flutter_polyline_points: ^2.0.0
  firebase_core: ^2.31.1

dev_dependencies: 
  flutter_lints: ^4.0.0
  flutter_test: 
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.3.3

flutter: 
  uses-material-design: true
  assets:
    - assets/anims/
